Pizza/ViewModels/EditPizza/EditIngredientsViewModel.cs
namespace Pizza.ViewModels;

public class EditIngredientsViewModel
{
    public IEnumerable<EditPizzasIngredientsViewModel> Ingredients { get; set; } = new List<EditPizzasIngredientsViewModel>();
}

Pizza/Areas/Admin/Controllers/EditIngredientsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Pizza.Services.Contracts;
using Pizza.ViewModels;

namespace Pizza.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = "Admin")]

public class EditIngredientsController : Controller
{
    private IAdminService _adminService;

    public EditIngredientsController(IAdminService adminService)
    {
        this._adminService = adminService;
    }
    // GET
    public async Task<IActionResult> Index()
    {
        var ingredients = await _adminService.GetAllIngredients();
        var model = new EditIngredientsViewModel()
        {
            Ingredients = ingredients
        };
        return View(model);
    }

    public async Task<IActionResult> DeleteIngredient(Guid id)
    {
        bool result = await _adminService.DeleteIngredient(id);
        return result ? RedirectToAction("Index") : View();
    }
}

Pizza/Areas/Admin/Views/EditIngredients/Index.cshtml
@using EditIngredientsViewModel = Pizza.ViewModels.EditIngredientsViewModel
@model EditIngredientsViewModel
<div class="container justify-content-center align-self-center mt-5">
    <a asp-controller="Home" asp-action="Index" class="btn btn-dark p-2 mb-1">← Back</a>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th scope="col">Ingredient Name</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var ing in Model.Ingredients)
        {
            <tr>
                <th scope="row">@ing.Name</th>
                <td>
                    <div class="d-flex align-items-center">
                        <div class="d-grid gap-2">
                            <a asp-controller="EditIngredients" asp-action="DeleteIngredient" asp-route-id="@ing.Id" class="btn btn-secondary">
                                <i class="fas fa-trash"></i> Delete
                            </a>
                        </div>
                    </div>
                </td>
            </tr>

        }
        </tbody>
    </table>
</div>